issues:
  exclude-rules:
    - path: internal/http/interceptors/log/log.go
      text: "SA1019:"
      linters:
        - staticcheck
    - path: pkg/utils/utils.go
      text: "SA1019:"
      linters:
        - staticcheck
linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    #- depguard
    - revive
    - goimports
    - unconvert
    - exportloopref
    - misspell
    - gocritic
    - prealloc
    #- gosec

linters-settings:
  revive:
    ignore-generated-header: true
    rules:
      - name: context-keys-type
      - name: time-naming
      - name: var-declaration
      - name: unexported-return
      - name: errorf
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
        # allow using ginkgo with dot imports
        Disabled: true
      - name: unused-parameter
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
